version: '3.9'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db

  server:
    container_name: server
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017
      DB_NAME: testdata

volumes:
  mongo_data:
